### ISSUE TITLE
Compiling on Linux?

### ISSUE THREAD

**Issue by tleb** [Loodoor/Unamed-Endive#7]
Je suis un peu déçu, les instructions sur la page "Compiling" sont des screenshots de Code::Blocks ; ça se passe comment pour compiler sous Linux ?

On ne pourrait pas avoir un `./configure` puis `make`?

**Comment by Loodoor** [comment]
hey !
pour les fichiers make, j'ai un générateur automatique qui les fait dans le dossier makefiles/ normalement (faudra que je pense à le mettre à jour parce que mes path sont en absolu, donc format windows même pour les makefiles unix)

ensuite perso sur mon ubuntu, j'ai code blocks et ce n'est que là dessus que je m'echine à compiler (parce que j'ai plein de problèmes avec les dépendances hélas). donc niveau configure/make je suis pas à l'aise du tout en fait x)

----

pour ce qui est du makefile dans makefiles/make.unix, il y a très peu de chemins à changer, ce sont ceux dans la variable `INC` et dans `LIBDIR`, qu'il faut ajuster pour les faire pointer sur la SFML-2.4.2 sur ton pc. python est déjà fourni, un seul bug qui va venir avec python est qu'il ne va pas trouver <io.h> (dans pyconfig.h si mes souvenirs sont bons), et il faut le faire pointer sur le io.h dans `/usr/include/sys/io.h` normalement)

**Comment by tleb** [comment]
[Stdout](http://paste.awesom.eu/ANyj&ln) et [stderr](http://paste.awesom.eu/ZEfj&ln) d'un `make -f makefiles/make.unix` (après les modifs que tu m'as indiqué). On dirait des erreurs de syntaxe, y'a des versions de C++ particulières à utiliser ? Il faut paramétrer ça ?

```
⟩ gcc --version
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)
```

**Comment by Loodoor** [comment]
Wow. Python a fait des siennes encore. Perso je compile en c++ 11 (option 1y) mais tu peux essayer en 14 (je pense pas que ca change quoi que ce soit, mais ca vaut la peine d'essayer).

Après d'après ce que je vois, ce merdier serait dû au fait que j'ai mis le code de Python 3.4 pour Windows, et non Linux. Parce que chez moi les LONG font du 4 en size, mais sur Linux j'en ai trouvé en 8 (or comme python vérifie les tailles, et qu'elles sont pas pareil, ca lance l'erreur, ce qui plante tout le reste)

Ce que je peux conseiller du coup, serait de faire un `sudo apt-get install python3.4` et de faire pointer l'installation de python (include et libs) sur ton installation perso. J'ajouterai ca dans le compiling.html si ca marche :)

**Comment by tleb** [comment]
Wouhou, [le stderr](http://paste.awesom.eu/cu8A&ln) est bien plus court ! Ça m'a tout l'air d'être une simple erreur de syntaxe/d'argument d'une partie du code que tu n'as pas pu tester.

**Comment by Loodoor** [comment]
Ah, pour ce qui est du code de création de répertoire, en fait, oublie. Je vais faire un patch pour passer par le scripting python très bientôt ^^ Je re post dès que c'est fixé

**Comment by Loodoor** [comment]
fix : https://github.com/Loodoor/Unamed-Endive/commit/55296cea6ec7bb21b8ab73a974088eb70cc1f74d

----

pour compiler tu as utiliser le make.unix ? si oui tu pourras également poster les modifs faites dessus et les commandes utilisées, que j'ajoute ca sur le site x) merci à toi ;) !

**Comment by tleb** [comment]
Après avoir bien galéré pour trouver un windres dispo sous Linux (il faut installer `mingw64-binutils` et `mingw64-gcc`), j'ai encore une erreur :

```
test -d bin/Debug || mkdir -p bin/Debug
test -d obj/Debug/src/scripting || mkdir -p obj/Debug/src/scripting
test -d obj/Debug/src/particles || mkdir -p obj/Debug/src/particles
test -d obj/Debug/src/objects || mkdir -p obj/Debug/src/objects
test -d obj/Debug/src/map || mkdir -p obj/Debug/src/map
test -d obj/Debug/src/map/blocks || mkdir -p obj/Debug/src/map/blocks
test -d obj/Debug/src || mkdir -p obj/Debug/src
test -d obj/Debug/src/entities || mkdir -p obj/Debug/src/entities
test -d obj/Debug/src/views || mkdir -p obj/Debug/src/views
test -d obj/Debug/src/views/huds || mkdir -p obj/Debug/src/views/huds
test -d obj/Debug/src/abstract || mkdir -p obj/Debug/src/abstract
test -d obj/Debug || mkdir -p obj/Debug
test -d obj/Debug/src/entities/effects || mkdir -p obj/Debug/src/entities/effects
test -d obj/Debug/src/bag/pockets || mkdir -p obj/Debug/src/bag/pockets
test -d obj/Debug/src/bag/pockets/objects || mkdir -p obj/Debug/src/bag/pockets/objects
test -d obj/Debug/src/bag || mkdir -p obj/Debug/src/bag
g++ -L/home/tleb/sd/Prog/other/SFML-2.4.2/lib -L/usr/lib/python3.4 -o bin/Debug/main obj/Debug/src/scripting/scripting.o obj/Debug/src/particles/particles.o obj/Debug/src/objects/dex.o obj/Debug/src/map/tilemap.o obj/Debug/src/map/reader.o obj/Debug/src/map/map.o obj/Debug/src/map/blocks/block.o obj/Debug/src/jsoncpp.o obj/Debug/src/game.o obj/Debug/src/entities/pnjmanager.o obj/Debug/src/views/view.o obj/Debug/src/views/save.o obj/Debug/src/views/map.o obj/Debug/src/views/inventory.o obj/Debug/src/views/huds/menu.o obj/Debug/src/views/huds/hud.o obj/Debug/src/views/fight.o obj/Debug/src/views/dex.o obj/Debug/src/views/default.o obj/Debug/src/views/creatures.o obj/Debug/src/abstract/triggersmanager.o obj/Debug/src/abstract/texturesmanager.o obj/Debug/src/abstract/statemachine.o obj/Debug/src/abstract/soundmanager.o obj/Debug/src/abstract/point.o obj/Debug/src/abstract/musicplayer.o obj/Debug/src/abstract/functions.o obj/Debug/src/abstract/equip.o obj/Debug/src/abstract/creatures_loader.o obj/Debug/src/abstract/competence.o obj/Debug/resource.o obj/Debug/main.o obj/Debug/src/entities/pnj.o obj/Debug/src/entities/effects/sort.o obj/Debug/src/entities/creature.o obj/Debug/src/entities/character.o obj/Debug/src/entities/animatedentity.o obj/Debug/src/constants.o obj/Debug/src/bag/pockets/pocket.o obj/Debug/src/bag/pockets/objects/object.o obj/Debug/src/bag/objectstable.o obj/Debug/src/bag/bag.o obj/Debug/src/abstract/types_table.o  -lPython34 -lsfml-graphics-d -lsfml-window-d -lsfml-audio-d -lsfml-system-d
obj/Debug/resource.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
makefiles/make.unix:83: recipe for target 'out_debug' failed
make: *** [out_debug] Error 1
```

**Comment by Loodoor** [comment]
faut que tu supprimes les vieux .o, comme la compilation a échoué ca a pu les corrompre ce qui cause l'erreur :)

**Comment by tleb** [comment]
Non, un autre fichier cause problème maintenant. [Stdout](http://paste.awesom.eu/6X10&ln) et [Stderr](http://paste.awesom.eu/fQCZ&ln). J'aurai plus de temps à dédier à ce problème dimanche.

**Comment by Loodoor** [comment]
trouvé ! il veut compiler resource.rc ce qui ne sert strictement à rien

**Comment by Loodoor** [comment]
un début de fix (`configure`) lié à ce problème : https://github.com/Loodoor/Unamed-Endive/commit/9def3e980a56d91cdf4bbfc0c4c0be15f868a08a

**Comment by tleb** [comment]
Le premier apt-get va pas marcher sur les non-debian et il manque un e à `python-devl`.

Le LDFLAGS `-lPython34` il doit contenir quoi ? Un path vers l'exécutable ?

**Comment by Loodoor** [comment]
Il ne contient rien, comme les flags `-lsfml-***-d` par exemple (ma commande de build est celle ci chez moi : 
`g++.exe -LC:\SFML-2.4.2\lib -Lsrc\scripting\Python34\libs -Ldlls\ -o bin\Debug\main.exe obj\Debug\main.o obj\Debug\src\abstract\competence.o obj\Debug\src\abstract\creatures_loader.o obj\Debug\src\abstract\equip.o obj\Debug\src\abstract\functions.o obj\Debug\src\abstract\musicplayer.o obj\Debug\src\abstract\point.o obj\Debug\src\abstract\soundmanager.o obj\Debug\src\abstract\statemachine.o obj\Debug\src\abstract\texturesmanager.o obj\Debug\src\abstract\triggersmanager.o obj\Debug\src\abstract\types_table.o obj\Debug\src\bag\bag.o obj\Debug\src\bag\objectstable.o obj\Debug\src\bag\pockets\objects\object.o obj\Debug\src\bag\pockets\pocket.o obj\Debug\src\constants.o obj\Debug\src\entities\animatedentity.o obj\Debug\src\entities\character.o obj\Debug\src\entities\creature.o obj\Debug\src\entities\effects\sort.o obj\Debug\src\entities\pnj.o obj\Debug\src\entities\pnjmanager.o obj\Debug\src\game.o obj\Debug\src\jsoncpp.o obj\Debug\src\map\blocks\block.o obj\Debug\src\map\map.o obj\Debug\src\map\reader.o obj\Debug\src\map\tilemap.o obj\Debug\src\objects\dex.o obj\Debug\src\particles\particles.o obj\Debug\src\scripting\scripting.o obj\Debug\src\views\creatures.o obj\Debug\src\views\default.o obj\Debug\src\views\dex.o obj\Debug\src\views\fight.o obj\Debug\src\views\huds\hud.o obj\Debug\src\views\huds\menu.o obj\Debug\src\views\inventory.o obj\Debug\src\views\map.o obj\Debug\src\views\save.o obj\Debug\src\views\view.o  obj\Debug\resource.res -lPython34  -lsfml-graphics-d -lsfml-window-d -lsfml-audio-d -lsfml-system-d`)

---

J'ai corrigé le premier apt-get, j'avais oublié. Sinon en quoi il manque un 'e' ? à la fin du nom du package ?

**Comment by Loodoor** [comment]
Fix : https://github.com/Loodoor/Unamed-Endive/commit/5200a642e65643f516e3b523730cf6d884ecee75 (avec correction sur les makefiles)

**Comment by tleb** [comment]
Je veux dire, c'est un link, mais il doit link vers quoi ? Python34 représente quoi ? Un fichier, un dossier ?

**Comment by Loodoor** [comment]
Normalement, rien. Ca parait bizarre je sais, mais chez moi ca fonctionne comme ca sans problème >.>

**Comment by tleb** [comment]
C'est bon, j'ai trouvé : c'est pour linker python-devel. Le problème, c'est que `python34-devel` n'existe pas sous Fedora et `python3-devel` est pour Python 3.5.2.

**Comment by Loodoor** [comment]
haan ...

essaye quand même de linker avec python3-devel pour voir, on verra bien (normalement le code du système de scripting accepte toutes les versions de python)

**Comment by tleb** [comment]
C'est bon, cette partie fonctionne, c'était juste que les filesystems sous Linux sont case-sensitive.

Le problème maintenant est avec `libjpeg` : `libsfml` en a besoin mais cherche une version précise : `libjpeg.so.8`. Or, quand on installe `libjpeg` sous Fedora, on récupère un `libjpeg.so`, un `libjpeg.so.62` et un `libjpeg.so.62.2.0`. J'ai essayé un lien symbolique, ça ne fonctionne pas. Donc, faut que je trouve où je peux télécharger `libjpeg.so.8`.
