### ISSUE TITLE
The music doesn't start

### ISSUE THREAD

**Issue by Typhlos** [Loodoor/Unamed-Endive#9]
Lorsqu'on appuie sur le bouton ```F6```, comme spécifié dans le wiki, la musique ne se lance pas dans le jeu.

**Comment by Loodoor** [comment]
Hey !

En mode debug (la release a été comme tel), la musique ne se lance pas automatiquement. En effet, F6, même si la musique a été coupée (ce qui est techniquement le cas en mode debug), elle doit se relancer. Je vais voir pourquoi

**Comment by Loodoor** [comment]
Corrigé par https://github.com/Loodoor/Unamed-Endive/commit/5ceca4b7d70cfbcf34285d6a965e8b5c795a680a
